Willlasbury/project-3-front

- src/pages/Signup/index.js
added password functionality to signup page
> Dsc signup

- src/App.js
- src/components/Navbar/index.js
- src/pages/Category/index.js
- src/pages/FreeItem/index.js
- src/pages/LookingFor/index.js
- src/pages/PostItem/index.js
added basic navbar links to new pages with H1 tags
> updated NavBar and app file added basic function with H1 tags

- src/App.js
- src/components/Navbar/index.js
- src/pages/Category/index.js
- src/pages/FreeItem/index.js
- src/pages/LookingFor/index.js
- src/pages/PostItem/index.js
- src/pages/Search/index.js
added search page and added to nav bar
> got a search page up and linked to nav

- src/components/UploadWidget.js
Please be sure to review as I am having pull issues
> added cloudinary upload widget for post item

- src/pages/Flip/index.js
- src/utils/API/items.js
added items.js in api and added fetch requests also added email on users fetch
> Dsc fetches

- src/components/Footer/index.js
- src/pages/Flip/index.js
- src/pages/Flip/style.css
- src/utils/API/items.js
- src/utils/API/users.js
added await words to the fetch and some styling to flip page
> added await words to the fetch and some styling to flip page

- src/components/UploadWidget.js
- src/utils/API/items.js
Added the post route on the upload widget so that it sends the new item
> added post route to item with photos

- src/components/UploadWidget.js
Adding inputs needed for posting an item and connected it to the back end route to create a new item
> Ah push photo

- src/App.js
- src/pages/Flip/index.js
- src/pages/Flip/style.css
> got flip to work

- src/App.js
- src/components/Category.js
- src/components/Navbar/index.js
- src/pages/YourItems/index.js
- src/utils/API/categories.js
- src/utils/API/users.js
added get item but user id. Just need to add the user id from the log in token once it is comepleted.
> Ah item pull

- src/pages/Browse/index.js
- src/pages/Item/index.js
Added multi Photo Functionality
> Ah multi photo

- src/components/Footer/index.js
- src/components/Navbar/index.js
- src/index.css
- src/pages/Browse/index.js
- src/pages/Item prop/index.js
- src/pages/Items/index.js
- src/pages/Login/index.js
- src/tailwind.config.js
Added individual Item page with fetch route
> Ah individual item

- src/components/UploadWidget.js
- src/pages/Items/index.js
- src/utils/API/items.js
Added multiple photos to post route
> added photo route

- src/pages/Item prop/index.js
added connection to individual page, fixed image load for individual page
> connected individual with browse

- src/components/Navbar/index.js
- src/components/UploadWidget.js
- src/pages/Browse/index.js
- src/pages/Flip/index.js
- src/pages/Flip/style.css
- src/pages/Item prop/index.js
- src/pages/Items/index.js
- src/pages/PostItem/index.js
changed styling on post item page
> Dsc styling5

- src/App.js
- src/components/UploadWidget.js
- src/pages/Browse/index.js
- src/pages/Category/index.js
- src/pages/FreeItem/index.js
- src/pages/Items/index.js
- src/pages/Login/index.js
- src/pages/Offer/index.js
- src/pages/PostItem/index.js
- src/pages/Search/index.js
- src/pages/Signup/index.js
- src/pages/YourItems/index.js
fixed image and margins to fit full screen
> Dsc styling6

- src/pages/Login/index.js
- src/pages/Signup/index.js
hidden password for login and signup
> hidden password on login and signup

- src/components/Footer/index.js
- src/components/Navbar/index.js
changed colors nav bar and footer
> Dsc styling10

- src/pages/Individual Items Page/index.js
- src/pages/Items/index.js
got photos same size on browse, items, and ind items page
> got photos same size on browse, items, and ind items page

- src/components/UploadWidget.js
- src/pages/ItemProp/index.js
- src/pages/ItemProp/style.css
> Dsc styling16

- src/components/Navbar/index.js
- src/pages/Flip/index.js
- src/pages/Flip/style.css
Got the coin flip page to rotate :)
> got flip page to make coin rotate

- src/App.js
- src/components/UploadWidget.js
- src/pages/Offer/index.js
- src/utils/API/items.js
Maybe getting rid of onBlur did something
> Wla frankenstein

- src/components/UploadWidget.js
Require all items to have all input fields have a value and at least one photo to create an item.
> Mic front branch

- src/components/UploadWidget.js
- src/pages/ItemProp/index.js
- src/pages/Items/index.js
- src/pages/Offer/index.js
- src/pages/YourItems/index.js
wanted the latest pull so I can work on the offer/item card
> Dsc styling21

- src/components/UploadWidget.js
- src/pages/Offer/index.js
- src/pages/edit item/index.js
added styling to offer and edit page
> added styling to offer and edit page

- .env
- src/App.js
- src/components/Navbar/index.js
- src/pages/edit item/index.js
- src/utils/socket/connection.js
add env var for socket connection
> final changes

- src/pages/edit item/index.js
Reroute from edit item page to your items page on click.
> Edit item rt

- src/components/Navbar/index.js
- src/pages/edit item/index.js
> Dsc styling24

- src/components/Offer/index.js
- src/components/YourOffers/index.js
- src/pages/Individual Items Page/index.js
- src/pages/ItemProp/index.js
- src/pages/Items/index.js
- src/pages/Notifications/index.js
added margins to match all around, added styling to notifications page
> added margins to match all around, added styling to notifications page
